### ISSUE TITLE
Ultimate Timber -> Smooth Timber

### ISSUE THREAD

**Issue by tommytran732** [Envel-Nikita-Gutsenkov/Goodmc.-Original.-Source-code.-#13]
Smooth Timber is made by the same devs as RWG, and the animation is also a lot better. Maybe we should switch to using it instead?

**Comment by Envel-Nikita-Gutsenkov** [comment]
these are the parts of our project that are mainly intended for our players. 
Ultimate Timber tree fall looks more realistic, it works more correctly with the fall of our trees and custom loot. in General, we are not ready to switch to an alternative, because it just doesn't make sense. even Ultimate Timber seems more functional
